export const retreatDirectory = [
  {
    id: "sri-lanka-2026",
    destination: "Sri Lanka",
    edition: "Sri Lanka Edition",
    venue: "Kurulu Bay",
    startDate: "2026-09-21",
    endDate: "2026-09-30",
    dates: "September 21-30, 2026",
    days: 10,
    nights: 9,
    route: "/sri-lanka",
    status: "Published",
    metadataComplete: true,
  },
  {
    id: "bali-september-2026",
    destination: "Bali",
    edition: "Bali September Edition",
    venue: "Dwa Chandra",
    startDate: "2026-09-23",
    endDate: "2026-09-29",
    dates: "September 23-29, 2026",
    days: 7,
    nights: 6,
    route: "/bali-september",
    status: "Published",
    metadataComplete: true,
  },
  {
    id: "bali-october-2026",
    destination: "Bali",
    edition: "Bali October Edition",
    venue: "Dwa Chandra",
    startDate: "2026-10-03",
    endDate: "2026-10-12",
    dates: "October 3-12, 2026",
    days: 10,
    nights: 9,
    route: "/bali-october",
    status: "Published",
    metadataComplete: true,
  },
];